import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Anonymous Baatein',
  description: 'Generated by create next app',
  icon : './favicon.ico'
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body className={inter.className}>
        <div className='max-w-3xl mx-auto p-4'>

          <Navbar />

          <div className='mt-8'>
            {children}
          </div>

          <Footer/>
        </div>
      </body>
    </html>
  )
}
